- .github/labeler.yaml
- .github/workflows/pr-labeler.yaml
[MVP-83](https://citz-imb.atlassian.net/browse/MVP-83)
> MVP-83: Create Automated Pull Request Labeler Task

- frontend/.eslintrc.cjs
Updated prettier rule because Standards was updated.
> Updated prettier rule

- example.env
- frontend/package.json
- frontend/src/AppRouter.tsx
- frontend/src/components/common/PageLayout.tsx
- frontend/src/components/common/index.ts
- frontend/src/css/base.css
- frontend/src/css/variables.css
- frontend/src/pages/Landing.tsx
- package.json
[MVP-95](https://citz-imb.atlassian.net/browse/MVP-95)
- Added `design-system` (experimental) package and added Header component.
- Adjusted styles.
- Added `PageLayout` component.
- Fixed scripts at root level.
> MVP-95: Added design-system header, adjusted styles, fixed scripts

- .github/workflows/dev-api-image-build.yaml
> MVP-80: Create Workflow to build, tag, push API to Artifactory

- .github/workflows/dev-api-image-build.yaml
Adding manual trigger for testing action.
> MVP-80: Automated CD Pipeline For CoCo API

- .github/workflows/dev-api-image-build.yaml
Adding test tag number for pipeline debugging
> MVP-80: Debug image tag number for testing pipeline

- frontend/src/components/common/Stack.tsx
- frontend/src/components/common/index.ts
- frontend/src/css/variables.css
- frontend/src/pages/Landing.tsx
[MVP-97](https://citz-imb.atlassian.net/browse/MVP-97)
Adds reusable `Stack` component for stacking components vertically or horizontally.
> MVP-97: Stack component

- .github/workflows/dev-api-image-build.yaml
Adding build arg via github action variable
> MVP-80: Adding Docker Build Arg For API Node Image

- backend/.docker/Dockerfile.prod
> MVP-80: Changing Docker Build Context

- backend/.docker/Dockerfile.prod
> MVP-80: Troubleshooting Docker npm install error

- frontend/src/components/common/ClickableCard.tsx
- frontend/src/components/common/index.ts
[MVP-98](https://citz-imb.atlassian.net/browse/MVP-98)
- Added `ClickableCard` component which can be imported from `components/common`.
Test in `pages/Landing` by importing and adding
``` JavaScript
<ClickableCard>
<p>Hello</p>
</ClickableCard>
```
> MVP-98: Added ClickableCard component

- .github/workflows/dev-api-image-build.yaml
- backend/Dockerfile.prod
> MVP-80: Copy of Dockerfile.prod one directory up

- .github/workflows/dev-api-image-build.yaml
> MVP-80: Typo!

- .github/workflows/dev-api-image-build.yaml
> MVP-80: Artifactory Push Troubleshooting

- .github/workflows/dev-api-image-build.yaml
> MVP-80: Removing bloat from Artifactory URL

- .github/workflows/dev-api-image-build.yaml
> MVP-80: Typo

- .github/workflows/dev-app-image-build.yaml
- frontend/Dockerfile.prod
> MVP-80: Build, tag, push ReactJS App to Artifactory

- .github/workflows/dev-app-image-build.yaml
> MVP-80: Typos

- .github/workflows/dev-app-image-build.yaml
[MVP-80](https://citz-imb.atlassian.net/browse/MVP-80
> MVP-80: Updating build args for frontend

- openshift/templates/api-dc-template.yaml
Created template to assist with deployment automation.
> MVP-80: Create api-dc-template.yaml

- openshift/templates/api-dc-template.yaml
Removing fields that will block automated deployment.
> MVP-80: Removing App DC Field Bloat

- openshift/templates/app-dc-template.yaml
Creating frontend application deployment config template.
> MVP-80: Create app-dc-template.yaml

- backend/src/express.ts
- backend/src/modules/github/controller.ts
- backend/src/modules/github/router.ts
- backend/src/modules/github/schemas.ts
- backend/src/modules/index.ts
- backend/src/utils/express-requests/validateRequestSchema.ts
[MVP-101](https://citz-imb.atlassian.net/browse/MVP-101)
Endpoint gives information on a GitHub repo's issues through use of the github api.
Test with Postman or ThunderClient (VSCode Extension) or similar by making a `GET` request to `http://localhost:6600/github/issues/citz-imb-common-code?state=open` while running the backend container.
Also fixed getParams and getQuery so they now return the correct error response.
> MVP-101: Added github issues endpoint

- .github/workflows/dev-api-deploy.yaml
> MVP-80: Create dev-api-deploy.yaml

- .github/workflows/dev-api-image-build.yaml
> MVP-80: Image Tag script type

- openshift/templates/api-dc-template.yaml
> MVP-80: So many typos

- openshift/templates/api-dc-template.yaml
> MVP-80: Re-naming template parameter

- openshift/templates/api-dc-template.yaml
> MVP-80: Cleaning Up API DC Template

- openshift/templates/api-dc-template.yaml
> MVP-80: Still more typos

- .github/workflows/dev-api-deploy.yaml
> MVP-80: Rollout Watch Correct Pod Reference

- openshift/templates/api-dc-template.yaml
> MVP-80: Change API DeployConfig Image Reference, Service Account

- .github/workflows/dev-api-image-build.yaml
> MVP-80: Update Hardcoded Image Tag

- backend/src/express.ts
> adam made me do it

- openshift/templates/api-dc-template.yaml
> MVP-80: Artifactory Image Reference Typo

- backend/src/express.ts
> all better

- openshift/templates/api-dc-template.yaml
> MVP-80: Update Image Pull Secret Reference

- openshift/templates/api-dc-template.yaml
> MVP-80: Update pull secret

- .github/workflows/dev-api-deploy.yaml
> MVP-80: Cleanup Dev Deploy Action

- .github/workflows/dev-app-image-build.yaml
> MVP-80: Updating Build, Tag Push Frontend Github Action

- .github/workflows/dev-app-image-build.yaml
> MVP-80: Wrong Image Tag Table Row Name

- compose.yaml
- frontend/index.html
- frontend/nginx.conf
- frontend/vite.config.ts
> MVP-80: Renaming API Reference to Match Kubernetes Service

- compose.yaml
- package.json
> MVP-80: API Container Naming

- openshift/templates/app-dc-template.yaml
> MVP-80: Updating Image and Image Pull Secret

- .github/dev-app-deploy.yaml
> MVP-80: Create APP Deploy Github Action

- openshift/templates/app-dc-template.yaml
> MVP-80: Many kinds, handle them

- frontend/index.html
> MVP-80: Intentionally Deploying a Bad

- frontend/index.html
> MVP-80: Redeploying a Good

- backend/src/index.ts
> MVP-80: Testing Deployment Pipeline

- frontend/index.html
> MVP-80: Testing for bad deployments

- openshift/templates/app-dc-template.yaml
> MVP-80: Remove ResourceID field to allow for re-deployment

- frontend/index.html
> MVP-80: Re-testing bad deployments

- frontend/index.html
> MVP-80: Re-testing Broken Re-Deployments

- backend/src/utils/express-requests/zodValidationMiddleware.ts
[MVP-131](https://citz-imb.atlassian.net/browse/MVP-131)
Fixed typo
> MVP-131: Fixed typos in zodValidationMiddleware

- openshift/templates/api-dc-template.yaml
> MVP-80: Vault Integration Secret Injection Into API DC Template

- .github/workflows/test-api-deploy.yaml
> MVP-80: Automate Deployment of API to TEST Environment

- .github/workflows/test-app-deploy.yaml
> MVP-80: Automate Deployment of Frontend to TEST Environment

- .github/workflows/test-api-deploy.yaml
> MVP-80: Changing Login Service Account to Default

- .github/workflows/test-api-deploy.yaml
> MVP-80: Secrets not Env

- .github/workflows/test-api-deploy.yaml
> MVP-80: Missed a secret reference

- .github/workflows/test-api-deploy.yaml
> MVP-80: It's Monday, did a bad

- .github/workflows/test-api-deploy.yaml
> MVP-80: Healthcheck Login Secret

- .github/workflows/test-api-deploy.yaml
> MVP-80: More secret references

- .github/workflows/dev-api-deploy.yaml
- .github/workflows/dev-app-deploy.yaml
> MVP-80: Bug in Image Tag Update Wiki Table

- .github/workflows/test-api-deploy.yaml
[MVP-80](https://citz-imb.atlassian.net/browse/MVP-)
> MVP-80: Quote Typo in TEST Update Wiki

- .github/workflows/test-app-deploy.yaml
> MVP-80: Cleanup TEST APP Deployment

- frontend/index.html
> MVP-80: Testing APP Deployment Pipeline to TEST

- .github/workflows/test-app-deploy.yaml
> MVP-80: Cleaning up copy pasta mistakes from API deploy

- .github/workflows/test-app-deploy.yaml
> MVP-80: Ugly bad typo

- .github/workflows/test-app-deploy.yaml
> MVP-80: Naming Convention

- openshift/templates/app-dc-template.yaml
> MVP-80: Adding Service Account to APP DC for image pull

- README.md
- frontend/src/css/base.css
[MVP-112](https://citz-imb.atlassian.net/browse/MVP-112)
- The `design-system` package already includes a button/link component that we can use.
- Removed existing button and a styles.
> MVP-112: Removed button and a styles

- openshift/templates/app-dc-template.yaml
> MVP-80: Removing Service Account From APP DC

- .github/workflows/test-app-deploy.yaml
> MVP-80: Specifying User Pre-deploy

- openshift/templates/app-dc-template.yaml
> MVP-80: New Image Pull Secret

- .github/helpers/deploy.sh
> MVP-80: Forgot to remove pipe

- openshift/templates/api-dc-template.yaml
> MVP-80: Missing Parameter/Env Var on API Template

- openshift/templates/api-dc-template.yaml
> MVP-80: Removing Image Pull Secret Field from API DC

- openshift/templates/app-dc-template.yaml
> MVP-80: Remove Image Pull Secret Field from APP DC

- .github/helpers/deploy.sh
- .github/workflows/dev-api-deploy.yaml
- .github/workflows/dev-app-deploy.yaml
- openshift/templates/api-dc-template.yaml
- openshift/templates/app-dc-template.yaml
> MVP-80: Adding Generic Pull Secret Credential to API/APP DC template

- .github/workflows/prod-app-deploy.yaml
> MVP-80: Automate APP deployment to PROD

- .github/workflows/prod-api-deploy.yaml
> MVP-80: Automate API deployment to PROD

- frontend/src/components/common/Heading/constants.ts
- frontend/src/components/common/Heading/index.tsx
- frontend/src/components/common/Heading/styleMapper.ts
- frontend/src/components/common/Heading/types.ts
- frontend/src/components/common/index.ts
[MVP-109](https://citz-imb.atlassian.net/browse/MVP-109)
Added `Heading` component.
Similar to `Typography` component but with added `divider` and `overline` props and with different sizing values.
```JavaScript
<Heading>Title</Heading>
```
---
```JavaScript
<Heading bold divider color="blue">Title</Heading>
```
---
```JavaScript
<Heading bold overline size="small">Discover BC</Heading>
```
---
```JavaScript
<Heading divider size="x-small">Title</Heading>
```
> - My changes …
> MVP-109: Added heading component

- openshift/templates/api-dc-template.yaml
> MVP-80: API env var updates

- openshift/templates/api-dc-template.yaml
Updated `ENVIRONMENT` env var value
> MVP-80: Changed ENVIRONMENT env var value

- backend/package.json
- frontend/package.json
[MVP-144](https://citz-imb.atlassian.net/browse/MVP-144)
Updating sso packages in an attempt to solve the sso cookie issue or to get more debug information.
> MVP-144: Updated sso packages

- frontend/package.json
[MVP-140](https://citz-imb.atlassian.net/browse/MVP-140)
Updated the following dependency updates: 
- vite
- @bcgov/design-system-react-components
- react-router-dom
- vite-tsconfig-paths
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser
- @types/node
- @types/react
- @types/react-dom
- eslint-plugin-react
- typescript
Ensured continers build and operate as expected
> MVP-140 Update frontend dependencies

- backend/package.json
[MVP-141](https://citz-imb.atlassian.net/browse/MVP-141)
Updated the following dependencies: 
- express
- @typescript-eslint/eslint-plugin
- @typescript-eslint/parser
- typescript
- @types/node
ensured containers built with no errors. 
> MVP-141: Update Backend Dependencies

- frontend/.eslintrc.cjs
- frontend/src/AppRouter.tsx
- frontend/src/components/common/Card/index.tsx
- frontend/src/components/common/Heading/index.tsx
- frontend/src/components/common/Icon/index.tsx
- frontend/src/components/common/PageLayout.tsx
- frontend/src/components/common/SectionCard/constants.ts
- frontend/src/components/common/SectionCard/index.tsx
- frontend/src/components/common/SectionCard/styleMapper.ts
- frontend/src/components/common/SectionCard/types.ts
- frontend/src/components/common/Spinner.tsx
- frontend/src/components/common/Spinner/index.tsx
- frontend/src/components/common/Spinner/styles.css
- frontend/src/components/common/Spinner/types.ts
- frontend/src/components/common/Stack/index.tsx
- frontend/src/components/common/Typography/index.tsx
- frontend/src/components/common/index.ts
- frontend/src/components/github/GitHubIssues/index.tsx
- frontend/src/components/github/GitHubIssues/types.ts
- frontend/src/components/github/IssueCard/constants.ts
- frontend/src/components/github/IssueCard/index.tsx
- frontend/src/components/github/IssueCard/styleMapper.ts
- frontend/src/components/github/IssueCard/types.ts
- frontend/src/components/github/index.ts
- frontend/src/components/icons/Authenticate/index.tsx
- frontend/src/css/variables.css
- frontend/src/pages/Landing.tsx
- frontend/src/pages/Package.tsx
- frontend/src/utils/endpoints.ts
- frontend/src/utils/formatTimeDifferenceString.ts
[MVP-102](https://citz-imb.atlassian.net/browse/MVP-102)
- Fixed `Card` component `onClick` prop
- Added `GitHubIssues` component
- Created page for `SSO React` and `SSO Express` package and added `GitHubIssues` component.
- Fixed `Spinner` animation
> MVP-102: GitHub Issues component

- openshift/templates/api-dc-template.yaml
> MVP-80: Troubleshooting Vault Init

- .github/helpers/deploy.sh
- .github/workflows/dev-api-deploy.yaml
- .github/workflows/prod-api-deploy.yaml
- .github/workflows/test-api-deploy.yaml
> MVP-80: Troubleshooting Vault Init Container

- backend/package.json
[MVP-145](https://citz-imb.atlassian.net/browse/MVP-145)
- Updated express package to `1.0.0-alpha3` to resolve cookie issue.
> MVP-145: Updated SSO packages

- frontend/.eslintrc.cjs
- frontend/src/components/cards/PackageCard/index.tsx
- frontend/src/components/cards/PackageCard/types.ts
- frontend/src/components/cards/index.ts
- frontend/src/components/text/Greeting/index.tsx
- frontend/src/components/text/index.ts
- frontend/src/pages/Landing.tsx
- frontend/src/utils/getTimeBasedGreeting.ts
- frontend/src/utils/index.ts
[MVP-99](https://citz-imb.atlassian.net/browse/MVP-99)
- Added `PackageCard` component
- Refactored `Landing` page to use `PackageCard`
- Made `Greeting` from `Landing` page to its own component
> MVP-99: SSO Card components

- .github/helpers/deploy.sh
- .github/workflows/prod-api-deploy.yaml
> MVP-80: Update Deploy Scipt to check for set vault environment variable

- backend/package.json
[MVP-144](https://citz-imb.atlassian.net/browse/MVP-144)
- Updated sso express package to `1.0.0-alpha4`
> MVP-144: Updated sso package

- frontend/src/components/common/Icon/constants.ts
- frontend/src/components/common/Icon/types.ts
- frontend/src/components/common/Modal/constants.ts
- frontend/src/components/common/Modal/index.tsx
- frontend/src/components/common/Modal/styleMapper.ts
- frontend/src/components/common/Modal/types.ts
- frontend/src/components/common/index.ts
- frontend/src/components/icons/Exit/index.tsx
- frontend/src/components/icons/Exit/types.ts
- frontend/src/components/icons/index.ts
- frontend/src/css/variables.css
[MVP-104](https://citz-imb.atlassian.net/browse/MVP-104)
- Added `Modal` component which includes `Exit` icon
> MVP-104: Added modal component

- frontend/index.html
> Updated title

- frontend/src/components/common/Modal/index.tsx
- frontend/src/components/common/Stack/constants.ts
- frontend/src/components/common/Stack/index.tsx
- frontend/src/components/common/Stack/styleMapper.ts
- frontend/src/components/common/Stack/types.ts
- frontend/src/components/github/IssueCard/index.tsx
- Added `spaceAround` `spaceBetween` and `spaceEvenly` props to `Stack` component.
> Added spacing props to Stack component

- .github/helpers/create-npm-dep-report.js
- Added hidden comments with data at the bottom of the issue body.
> NPM Dependency Report Workflow - Hidden comments

- .gitignore
- backend/__tests__/unit/utils/express-requests/HttpError.test.ts
- backend/__tests__/unit/utils/express-requests/errorWrapper.test.ts
- backend/__tests__/unit/utils/express-requests/httpStatusCode.test.ts
- backend/__tests__/unit/utils/express-requests/validateZodRequestSchema.test.ts
- backend/__tests__/unit/utils/express-requests/zodValidationMiddleware.test.ts
- backend/jest.config.ts
- backend/package.json
- backend/src/utils/index.ts
- backend/tsconfig.json
- Updated `tsconfig` to match IMB Developer Principles
- Added jest config to backend
- Added unit tests for `utils/express-requests`
- Updated sso express package to alpha5
Test with `npm run test:unit` in the `backend`
> MVP-155: Part1 - Added jest config and some unit tests

- README.md
> Updated readme with volume mount info

- backend/src/modules/github/controller.ts
- frontend/src/components/github/IssueCard/index.tsx
- The `url` properties were urls to the github api, not the actual repo or profile.
> Fix github issues urls

- backend/__tests__/unit/utils/logging/colors.test.ts
- backend/__tests__/unit/utils/logging/debugStatements.test.ts
- backend/__tests__/unit/utils/logging/getCurrentDateTime.test.ts
- backend/__tests__/unit/utils/logging/logMessages.test.ts
- backend/__tests__/unit/utils/zod.test.ts
- backend/jest.config.ts
- backend/src/utils/logging/getCurrentDateTime.ts
- backend/src/utils/zod.ts
> MVP-155: Part2: Remaining utils unit tests

- backend/__tests__/unit/modules/config/controller.test.ts
- backend/__tests__/unit/modules/github/controller.test.ts
- backend/__tests__/unit/modules/github/schemas.test.ts
- backend/__tests__/unit/modules/health/controller.test.ts
> MVP-155: Part3 - Added module unit tests

- backend/__tests__/unit/config/auth.test.ts
- backend/__tests__/unit/config/cors.test.ts
- backend/__tests__/unit/config/rateLimit.test.ts
- backend/src/express.ts
> MVP-155: Part4 - Added config unit tests

- backend/__tests__/integration/github/router.test.ts
- backend/__tests__/unit/modules/github/controller.test.ts
- backend/jest.config.ts
- backend/tsconfig.json
- Ignored build directory when running tests
- Fixed github endpoint tests
> MVP-155: Fixed tests

- backend/package.json
> Changed prod npm script

- backend/package.json
- frontend/package.json
[MVP-126](https://citz-imb.atlassian.net/browse/MVP-126)
Updated sso package versions.
> MVP-126: Updated sso packages

- openshift/templates/api-dc-template.yaml
[MVP-194](https://citz-imb.atlassian.net/browse/MVP-194)
> MVP-194: API Resource Defintion

- openshift/templates/api-dc-template.yaml
[MVP-196](https://citz-imb.atlassian.net/browse/MVP-196)
> MVP-196: Adding Readiness/Liveness Probe to API Container 

- openshift/templates/app-dc-template.yaml
[MVP-197](https://citz-imb.atlassian.net/browse/MVP-197)
> MVP-197: Adding Readiness/Liveness Probes to Frontend Container

- openshift/templates/api-dc-template.yaml
[MVP-196](https://citz-imb.atlassian.net/browse/MVP-196)
> MVP-196: Deploy Troubleshooting

- openshift/templates/app-dc-template.yaml
[MVP-196](https://citz-imb.atlassian.net/browse/MVP-196)
> MVP-196: Tab Typo Troubleshooting

- openshift/templates/app-dc-template.yaml
[MVP-197](https://citz-imb.atlassian.net/browse/MVP-197)
> MVP-197: Troubleshoot Frontend Deployment

- openshift/templates/api-dc-template.yaml
[MVP-194](https://citz-imb.atlassian.net/browse/MVP-194)
> MVP-194: Re-doing container resource request/limit

- openshift/templates/app-dc-template.yaml
[MVP-195](https://citz-imb.atlassian.net/browse/MVP-195)
> MVP-195: Re-doing container resource request/limit

- openshift/templates/api-hpa-template.yaml
[MVP-203](https://citz-imb.atlassian.net/browse/MVP-203)
> MVP-203: Create API HPA Template

- openshift/templates/app-hpa-template.yaml
[MVP-204](https://citz-imb.atlassian.net/browse/MVP-204)
> MVP-204: Create App HPA Template

- openshift/templates/api-service-route-template.yaml
[MVP-207](https://citz-imb.atlassian.net/browse/MVP-207)
> MVP-207: Create Template for API Service and Routes

- openshift/templates/app-service-route-template.yaml
[MVP-208](https://citz-imb.atlassian.net/browse/MVP-208)
> MVP-208: Create Template for App Service and Route

- example.env
- frontend/__tests__/setupTests.ts
- frontend/__tests__/unit/Breadcrumbs/Breadcrumbs.test.tsx
- frontend/__tests__/unit/Breadcrumbs/Crumb.test.tsx
- frontend/__tests__/unit/Breadcrumbs/makecrumbs.test.tsx
- frontend/jest.config.ts
- frontend/package.json
- frontend/scripts/run-coverage-and-open-report.mjs
- frontend/src/Router.tsx
- frontend/src/components/RootLayout/RootLayout.tsx
- frontend/src/components/cards/PackageCard/PackageCard.tsx
- frontend/src/components/cards/PackageCard/types.ts
- frontend/src/components/common/Card/Card.tsx
- frontend/src/components/common/Heading/Heading.tsx
- frontend/src/components/common/Icon/Icon.tsx
- frontend/src/components/common/Modal/Modal.tsx
- frontend/src/components/common/SectionCard/SectionCard.tsx
- frontend/src/components/common/Stack/Stack.tsx
- frontend/src/components/common/Typography/Typography.tsx
- frontend/src/components/github/GitHubIssues/GitHubIssues.tsx
- frontend/src/components/github/IssueCard/IssueCard.tsx
- frontend/src/components/text/Greeting/Greeting.tsx
- frontend/src/constants/packages/types.ts
- frontend/src/main.tsx
- frontend/src/pages/Landing.tsx
- frontend/src/pages/Package.tsx
- frontend/tsconfig.json
- Added example env vars for css api package
- Added coverage script `npm run coverage:open`
- Updated testing config for paths
- Updated tsconfig to match IMB Dev Standards
> Testing and path updates

- backend/package.json
- Not updating `eslint` because of peer dependency issues
> Backend dependency updates

- frontend/package.json
- Omitted `eslint` update because of peer dependency issues.
> Frontend dependency updates

- frontend/src/Router.tsx
- frontend/src/components/RootLayout/RootLayout.tsx
- frontend/src/components/cards/PackageCard/PackageCard.tsx
- frontend/src/constants/packages/packages.ts
- frontend/src/pages/Landing/Landing.tsx
- frontend/src/pages/Landing/index.ts
- frontend/src/pages/Landing/styles.css
[MVP-214](https://citz-imb.atlassian.net/browse/MVP-214)
- I talked with Laura and we decided to change some of the text on the package cards and pages.
- I also improved the responsiveness of the package cards on the landing page.
> MVP-214: Updated spacing and text

- frontend/package.json
- frontend/src/constants/packages/packages.ts
[MVP-214](https://citz-imb.atlassian.net/browse/MVP-214)
- Updated summary text on package card
- Updated sso react package
> MVP-214: Updated text and sso react package

- openshift/templates/api-dc-template.yaml
> Reducing Memory Limit on API DC to Avoid silent deploy failures

- .github/workflows/update-image-tag-api-dev.yaml
> MVP-248: Create Script to Update Gitops API Image Tag in Dev

- frontend/__tests__/unit/components/common/Section.test.tsx
- frontend/__tests__/unit/components/common/Tabs.test.tsx
- frontend/__tests__/unit/components/github/GitHubTabs.test.tsx
- frontend/__tests__/unit/pages/Landing.test.tsx
- frontend/src/components/common/Heading/constants.ts
- frontend/src/components/common/Heading/types.ts
- frontend/src/components/common/Section/Section.tsx
- frontend/src/components/common/Section/constants.ts
- frontend/src/components/common/Section/index.ts
- frontend/src/components/common/Section/styleMapper.ts
- frontend/src/components/common/Section/types.ts
- frontend/src/components/common/index.ts
- frontend/src/constants/packages/packages.ts
- frontend/src/constants/packages/types.ts
- frontend/src/pages/Landing/Landing.tsx
[MVP-246](https://citz-imb.atlassian.net/browse/MVP-246)
> MVP-246: Add section component

- .github/workflows/update-image-tag-api-dev.yaml
> MVP-248: Forgot to change yaml field to correctly update

- backend/src/index.ts
> MVP-248: Troubleshoot API image tag update

- .github/workflows/update-image-tag-api-dev.yaml
> MVP-248: Adam made a dumb

- .github/workflows/update-image-tag-api-dev.yaml
> MVP-248: Dyslexia Strikes Back

- backend/src/index.ts
> MVP-248: Troubleshooting

- .github/workflows/update-image-tag-api-dev.yaml
- .github/workflows/update-image-tag-frontend-dev.yaml
> MVP-248: Creating Script to Update GitOps Frontend Image Tag Value

- frontend/index.html
> MVP-248: Testing Frontend Image Tag Update/Deploy to Dev

- backend/src/index.ts
> MVP-248: Testing Update Wiki Jobs

- .github/workflows/update-image-tag-api-dev.yaml
> MVP-248: Updating User for Update Wiki

- backend/src/index.ts
> MVP-248: Troubleshooting Update Wiki Action

- .github/workflows/update-image-tag-api-dev.yaml
> MVP-248: Troubleshooting Github Login in Action

- backend/src/index.ts
> MVP-248: Updating API Image to Test Update WIki Action

- .github/workflows/update-image-tag-api-dev.yaml
> MVP-248: Removing Update Wiki Jobs

- .github/workflows/update-image-tag-api-test.yaml
> MVP-248: Creating Action to Update TEST API Image Tag in GitOps Repo

- .github/workflows/update-image-tag-api-test.yaml
> MVP-248: Typo In Action name

- .github/workflows/update-image-tag-frontend-test.yaml
> MVP-248: Create Script to Update Frontend Image Tag in GitOps Repo

- .github/workflows/update-image-tag-api-prod.yaml
> MVP-248: Create Script to Update PROD API Image Tag in GitOps Repo

- .github/workflows/update-image-tag-frontend-prod.yaml
> MVP-248: Create Script to Update PROD Frontend Image tag in GitOps Repo

- backend/src/index.ts
> MVP-248: Testing Update Action

- .github/workflows/update-image-tag-frontend-dev.yaml
> MVP-248: Update Image Tag Wiki Table for Frontend Image

- frontend/index.html
> MVP-248: Testing Update Wiki Table Action

- .github/workflows/update-image-tag-api-test.yaml
> MVP-248: Updating API TEST Image Tag in Wiki Table

- .github/workflows/update-image-tag-frontend-dev.yaml
> MVP-248: Updating Wrong Row/Column for APP Image Tag in Wiki Table

- .github/workflows/update-image-tag-api-prod.yaml
> MVP-248: Update PROD API Image Tag in Wiki Table

- .github/workflows/update-image-tag-frontend-prod.yaml
> MVP-248: Update PROD APP Image Tag in Wiki Table

- .github/workflows/update-image-tag-api-test.yaml
> MVP-248: Update TEST APP Image Tag in Wiki Table

- .github/workflows/api-test-coverage-report.yaml
> MVP-226: Create Code Climate Integration for Test Coverage

- .github/workflows/update-image-tag-frontend-dev.yaml
> MVP-248: Missing Github Token pt.3?

- .github/workflows/update-image-tag-frontend-prod.yaml
> MVP-248: Missing Github Token?

- .github/workflows/update-image-tag-frontend-test.yaml
> MVP-248: Missing Github Token pt.2?

- frontend/package.json
[MVP-232](https://citz-imb.atlassian.net/browse/MVP-232)
> MVP-232: Updated SSO React to 1.0.0-beta

- frontend/__tests__/unit/pages/Package.test.tsx
- frontend/src/Router.tsx
- frontend/src/constants/packages/packages.ts
- frontend/src/constants/packages/types.ts
- frontend/src/pages/Package.tsx
[MVP-265](https://citz-imb.atlassian.net/browse/MVP-265)
- Added documentation link as part of package constants
> MVP-265: Updated links to documentation

- .github/workflows/api-test-coverage-report.yaml
- .github/workflows/test-coverage-report.yaml
- frontend/__tests__/unit/utils/formatDateString.test.ts
- frontend/src/utils/formatDateString.ts
> MVP-226: Upload API coverage to Github

- .github/workflows/test-coverage-report.yaml
> MVP-226: Code Climate Action Cleanup

- .github/workflows/ci-api-unit-integration-test.yaml
> MVP-226: API CI Test Suite Action

- .github/workflows/ci-frontend-unit-integration-test.yaml
> MVP-226: Create CI Action for Frontend Unit Test Suite

- backend/src/index.ts
> MVP-226: Undo adam do stuff

- README.md
> MVP-226: Badge Update

- .github/workflows/ci-unit-integration-test.yaml
> MVP-226: If/Else Typo

- .github/workflows/ci-unit-integration-test.yaml
> MVP-226: Fetch depth for Output Logic

- .github/workflows/ci-unit-integration-test.yaml
> MVP-226: Troubleshooting Output

- .github/workflows/ci-unit-integration-test.yaml
> MVP-226: Indentation/Spacing Errors

- .github/workflows/ci-unit-integration-test.yaml
> MVP-226: Fix ci job

- frontend/index.html
- frontend/src/pages/Landing/Landing.tsx
> MVP-226: Brady did it

- frontend/src/pages/Landing/Landing.tsx
> MVP-226: Undid the thing

- .github/workflows/ci-unit-integration-test.yaml
> MVP-226: Update Path Requirements for CI

- backend/package.json
- frontend/package.json
[MVP-326](https://citz-imb.atlassian.net/browse/MVP-326)
> MVP-326: Updated sso packages

- .github/workflows/update-image-tag-api-test.yaml
> Test Promotion Typo In Log Output

- .codeclimate.yml
> Added code climate conf

- .codeclimate.yml
[MVP-348](https://citz-imb.atlassian.net/browse/MVP-348)
> MVP-348: Adding FixMe Plugin to Code Climate Config

- .codeclimate.yml
> Made an Oopsie
